### ISSUE TITLE
Please add `SMTP` support 

### ISSUE THREAD

**Issue by Muzammal01** [199ocero/mailifyflow#2]
I added Hostinger SMTP, but it's not working.

**Comment by 199ocero** [comment]
Hello @Muzammal01 the one I only tested is for `AWS SES` and can't guarante that other smtp provider will work. I have also added this note in the read me docs.

`To track email delivery, bounces, clicks, opens, etc., please ensure you add your AWS key, secret, region, and configuration set name in the .env variable. The system is currently configured only for Amazon SES and if you don't want to track any of this and just want to send emails, you can try adding another SMTP server, but I cannot guarantee it will work.`

**Comment by Muzammal01** [comment]
Hi @199ocero, I tried Hostinger SMTP and created a test campaign, and I received the email in my inbox.
![Screenshot 2024-12-25 123205](https://github.com/user-attachments/assets/0bd99f72-1da3-4732-98e5-108916345a5c)

Please help me with `MAILIFYFLOW_NODE_PATH=`. I added the node_modules path, but it's not working. Please tell me what I should add for `MAILIFYFLOW_NODE_PATH=` here.

**Comment by 199ocero** [comment]
@Muzammal01  if you are using mac/ubuntu you check the path via `which node` in the cli. If you are in windows I'm not sure how to do it as my machine is mac.

This is how it works in my Mac:
```env
MAILIFYFLOW_NODE_PATH='/Users/jay-areocero/.nvm/versions/node/v20.3.1/bin/node'
```

If you are using hostinger, I'm not sure how do you find the path of node if you can ssh it then `which node` command will give you the path.

**Comment by Muzammal01** [comment]
@199ocero , Thank you so much for guiding me. I installed Node.js on the Hostinger server using SSH, and then I ran `which node`, and I found the path, and it worked.
